[package]
name = "qr-fountain-gen"
version = "0.1.0"
authors = ["Slesarev <slesarew@gmail.com>"]
edition = "2018"

[dependencies]
raptorq = "1.6.3"
qrcodegen = "1.6.0"
apng-encoder = "0.3.0"
hex = "0.4.3"
num-integer = "0.1.41"

